import streamlit as st
import urllib.request
import time
import os

# Forcefully disable CrewAI telemetry for offline Air-Gapped execution
os.environ["CREWAI_TELEMETRY_OPT_OUT"] = "true"
os.environ["OTEL_SDK_DISABLED"] = "true"

# Import your powerful backend engine directly from your main.py file!
from main import MASController, seed_synthetic_datasets

# --- DYNAMIC STATUS CHECKERS ---
def check_llm_status() -> bool:
    """Pings the local Ollama server to see if it is actually running."""
    try:
        # A quick 1-second ping to the local AI
        with urllib.request.urlopen("http://127.0.0.1:11434/api/tags", timeout=1) as response:
            return response.status == 200
    except Exception:
        return False

def check_data_status() -> bool:
    """Checks if the synthetic databases have been generated."""
    return (os.path.exists("server_logs.json") and 
            os.path.exists("audio_scan_results.json") and 
            os.path.exists("video_scan_results.json"))

def main():
    st.set_page_config(page_title="Project Sentinel", page_icon="🛡️", layout="wide")
    
    # --- UI UPGRADE 1: DYNAMIC GLOBAL SIDEBAR ---
    with st.sidebar:
        st.image("https://img.icons8.com/color/96/000000/cyber-security.png", width=80)
        st.header("⚙️ System Status")
        
        # 1. Live LLM Check
        if check_llm_status():
            st.success("🟢 Llama 3.1: Online (Local)")
        else:
            st.error("🔴 Llama 3.1: OFFLINE")
            st.caption("Please start Ollama before deploying agents.")
            
        # 2. Live Database Check
        if check_data_status():
            st.success("🟢 Data Bootstrapping: Active")
        else:
            st.warning("🟡 Data Bootstrapping: Pending")
            
        st.info("🛡️ Sentinel MAS Ready")
        st.divider()
        st.caption("Developed for Digital Countermeasure Unit")

    st.title("🛡️ Project Sentinel: MAS Dashboard")
    st.write("Enter the cyber incident report below to deploy the AI Countermeasure Unit.")

    user_input = st.text_area("Incident Report:", height=150)

    if st.button("Deploy Agents"):
        # Prevent the user from running the system if the AI is offline
        if not check_llm_status():
            st.error("🚨 Critical Error: Local LLM is offline. Cannot deploy agents.")
            return

        if user_input:
            
            # --- UI UPGRADE 2: INTERACTIVE STATUS BOX ---
            with st.status("🚨 Threat Detected. Deploying Countermeasure Unit...", expanded=True) as status:
                st.write("🔍 Scanning network logs...")
                st.write("🧠 Engaging Dynamic Router...")
                st.write("🤖 Agents analyzing vectors... (Max 180s)")
                
                # Execute the backend pipeline you built in main.py
                controller = MASController(incident_report=user_input)
                result = controller.execute_pipeline()
                
                status.update(label="✅ Analysis Complete!", state="complete", expanded=False)
                
            if result.get("status") == "OK":
                data = result.get("final_output", {})
                
                # --- UI UPGRADE 3: ORGANIZED TABS ---
                tab1, tab2 = st.tabs(["📊 Executive Report", "🛠️ Developer Tools"])
                
                with tab1:
                    col1, col2 = st.columns(2)
                    with col1:
                        confidence = data.get("confidence_score", 0)
                        try:
                            conf_percent = float(confidence)
                            if conf_percent <= 1.0:
                                conf_percent = int(conf_percent * 100)
                        except:
                            conf_percent = confidence
                        st.metric(label="🎯 AI Confidence Level", value=f"{conf_percent}%")
                    with col2:
                        st.metric(label="⏱️ Execution Time", value=f"{result['runtime_seconds']}s")
                        
                    st.subheader("🔍 Threat Analysis")
                    st.info(data.get("analysis_result", "N/A"))
                    
                    st.subheader("🚀 Required Actions")
                    next_steps = data.get("next_step", "No steps provided.")
                    
                    if isinstance(next_steps, dict):
                        for key, val in next_steps.items():
                            st.markdown(f"**{str(key).replace('_', ' ').title()}**: {val}")
                    elif isinstance(next_steps, list):
                        for item in next_steps:
                            st.markdown(f"- {item}")
                    else:
                        st.write(next_steps)
                        
                with tab2:
                    st.write("Raw JSON Data Structure Generated by CrewAI:")
                    st.json(result)

            else:
                st.error("⚠️ System Degraded! Fallback Triggered.")
                st.error(result.get("error_log", "Unknown Error"))
                with st.expander("View System State"):
                    st.json(result)
        else:
            st.warning("Please enter an incident report first.")

if __name__ == "__main__":
    # Ensure datasets exist before the UI loads
    seed_synthetic_datasets()
    main()